version: "3.8"

services:
  nginx-port8080: 
    container_name: nginx-port8080
    image: nginx:latest
    ports:
      - "8080:80"
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 50M
        limits:
          cpus: "0.5"
          memory: 100M