version: "3.8"

services:
  postgres-example:
    container_name: postgres-example
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
    networks:
      - network-example

networks:
  network-example:
    name: network-example
    driver: bridge