version: "3.8"

services:

  # short syntax
  postgres-example1:
    container_name: postgres-example1
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - "postgres-data1:/var/lib/postgresql/data"
  
  # long syntax
  postgres-example2:
    container_name: postgres-example2
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - type: volume
        source: "postgres-data2"
        target: "/var/lib/postgresql/data"
        read_only: false

volumes:
  postgres-data1:
    name: postgres-data1
  postgres-data2:
    name: postgres-data2