version: "3.8"

services:
  flask-app:
    container_name: flask-app
    build: 
      context: "./app"
      dockerfile: Dockerfile
    image: "flask-app:1.0"
    environment:
      - "APP_PORT=5000"
    ports:
      - "5000:5000"
